[workspace]
members = [
    "zkevm-circuits",
    "bus-mapping",
    "keccak256",
    "geth-utils",
]

[patch.crates-io]
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "9dd1bffa760cdfba123d451010b9ad2af3d463a1" }
