[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.11"
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", rev = "9d3ab0cf7be57a828df6cedb8f58476b483fdde1" }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
bigint = "4"
num = "0.4"
sha3 = "0.10"
digest = "0.7.6"
array-init = "2.0.0"
paste = "1.0"
bus-mapping = { path = "../bus-mapping"}
eth-types = { path = "../eth-types" }
ethers-core = "0.6"
serde_json = "1.0.66"
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10.3"
lazy_static = "1.4"
keccak256 = { path = "../keccak256"}
# ecdsa = { git = "https://github.com/appliedzkp/halo2wrong.git", rev = "00b90e8c3198de0a73cdb6308f7dbea2bd6f24cc", features = ["kzg"] }
ecdsa = { path = "../../halo2wrong/ecdsa", features = ["kzg"] }
secp256k1 = { path = "../../halo2wrong/ecc/secp256k1", features = ["kzg"] }
ecc = { path = "../../halo2wrong/ecc/circuit", features = ["kzg"] }
maingate = { path = "../../halo2wrong/maingate", features = ["kzg"] }
integer = { path = "../../halo2wrong/integer", features = ["kzg"] }
group = "0.11"
k256 = "0.10.4"
generic-array = "0.12.4"
libsecp256k1 = "0.7"

[dev-dependencies]
criterion = "0.3"
hex = "0.4.3"
mock = { path = "../mock" }
itertools = "0.10.1"
pretty_assertions = "1.0.0"

[[bench]]
name = "binary_value"
harness = false

[features]
default = []
test = []
